// ns-fixture: a test NS_ART for the new-style engine (card ns-scenery-engine; docs/design/new-style/engine.md), made here as
// PNG pictures in flat marker colours, so tools/check.mjs can read back where the engine put each thing. Never shipped: it
// stands in for the packs the wire cards will make, and it is not art.
//   nsFixture() -> { data: the NS_ART object, text: the file as 21zc-data-nsart.js would hold it, COL: the marker colours }
//   png(w, h, fn) -> Buffer   fn(x, y) -> [r, g, b, a]
import zlib from 'node:zlib';
import { b91Encode } from './b91.mjs';

export function png(w, h, fn) {
  const raw = Buffer.alloc((w * 4 + 1) * h);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const p = fn(x, y), o = y * (w * 4 + 1) + 1 + x * 4; raw[o] = p[0]; raw[o + 1] = p[1]; raw[o + 2] = p[2]; raw[o + 3] = p[3]; }
  const chunk = (type, data) => { const len = Buffer.alloc(4), crc = Buffer.alloc(4), td = Buffer.concat([Buffer.from(type), data]); len.writeUInt32BE(data.length); crc.writeUInt32BE(zlib.crc32(td)); return Buffer.concat([len, td, crc]); };
  const ih = Buffer.alloc(13); ih.writeUInt32BE(w, 0); ih.writeUInt32BE(h, 4); ih[8] = 8; ih[9] = 6;
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ih), chunk('IDAT', zlib.deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}
const pic = (w, h, fn) => b91Encode(png(w, h, fn));
const CLEAR = [0, 0, 0, 0], INK = [12, 8, 20, 255];
// marker colours: the scenery's far layer (blue), its ground (green, from the seat line down), its fore layer (gold, the last
// rows), sprites (one colour per piece kind)
export const COL = { far: [40, 60, 120], ground: [60, 150, 50], fore: [210, 180, 60], foe: [200, 60, 60], node: [150, 100, 40], prop: [120, 120, 200],
  npc: [220, 220, 220], station: [170, 120, 70], gatherer: [80, 200, 200], critter: [240, 120, 220], camp: [90, 160, 90] };
// a scenery set: 960 x 540 picture px, seat line at row 432 (80%), safe columns 240-720
function scenery(ground) {
  const W = 960, H = 540, GY = 432;
  return { w: W, h: H, gy: GY, safe: [240, 720], lights: [[480, 260, 40, '255,200,120', 0.3]],
    layers: [{ img: 'far', par: 0.2 }, { img: 'ground', par: 1 }, { img: 'fore', par: 1.35, fore: 1 }],
    img: { far: pic(W, H, () => [...COL.far, 255]), ground: pic(W, H, (x, y) => (y >= GY ? [...ground, 255] : CLEAR)), fore: pic(W, H, (x, y) => (y >= 528 ? [...COL.fore, 255] : CLEAR)) } };
}
// a sprite sheet: frames side by side, each w x h art px, its anchor at the bottom row's centre; a 1 px ink outline round a
// filled body, a shade per frame so each frame reads apart
function sheet(names, w, h, col, more = {}) {
  const f = {}, n = names.length;
  names.forEach((k, i) => { f[k] = [i * w, 0, w, h, w >> 1, h - 1]; });
  const img = pic(w * n, h, (x, y) => {
    const i = Math.floor(x / w), lx = x % w, k = 1 - i * 0.06, inside = lx >= 4 && lx < w - 4 && y >= 6;
    if (!inside) return CLEAR;
    if (lx === 4 || lx === w - 5 || y === 6 || y === h - 1) return INK;
    return [Math.round(col[0] * k), Math.round(col[1] * k), Math.round(col[2] * k), 255];
  });
  return { f, img: { sheet: img }, ...more };
}
export function nsFixture() {
  const foe = () => sheet(['idle', 'advance', 'wind1', 'strike1', 'wind2', 'strike2', 'hurt', 'defeat'], 48, 96, COL.foe, { head: -90, hit: [0, -48], strike: [20, -50], lights: [[6, -80, 3, '255,80,80']] });
  const data = {
    v: 1,
    scenery: { 'fight.0': scenery(COL.ground), 'gather.gwoods': scenery(COL.ground), camp: scenery(COL.camp) },
    foe: { imp: foe(), 'slime.elder': foe(), gloomjaw: foe(), 'bat.elder': foe() },
    node: { 'wood.1': sheet(['idle', 'spent'], 64, 120, COL.node, { contact: { wren: [-18, -40], tobin: [-18, -40], pip: [-18, -40] }, chips: [-10, -50], glint: [0, -60] }) },
    prop: { 'pile.logs': sheet(['p0', 'p2', 'p4'], 40, 24, COL.prop), fire: sheet(['cold', 'lit0', 'lit1'], 32, 24, COL.prop, { fps: 6 }), stake: sheet(['idle'], 12, 30, COL.prop),
      tent: sheet(['idle'], 60, 50, COL.prop), pack: sheet(['idle'], 20, 24, COL.prop) },
    npc: { hesketh: sheet(['idle', 'lit'], 48, 100, COL.npc) },
    station: Object.fromEntries(['tavern', 'watch', 'bench', 'forge', 'store', 'loom', 'ench', 'library', 'shrine'].map(k => [k, sheet(['idle'], 96, 80, COL.station)])),
    gatherer: { bracken: sheet(['idle', 'rest'], 48, 96, COL.gatherer) },
    critter: { cr_moth: sheet(['idle0', 'idle1', 'hop0', 'hop1'], 20, 16, COL.critter) }
  };
  const lit = v => typeof v === 'string' ? `'${v}'` : Array.isArray(v) ? `[${v.map(lit).join(',')}]` : v && typeof v === 'object' ? `{${Object.entries(v).map(([k, x]) => JSON.stringify(k) + ':' + lit(x)).join(',')}}` : JSON.stringify(v);
  const text = `// 21zc-data-nsart: GENERATED by tools/lib/ns-fixture.mjs for tools/check.mjs (ns-scenery-engine). Never shipped.\nconst NS_ART = ${lit(data)};\n`;
  return { data, text, COL };
}
