"""Ability icons: deterministic conversion of Codex's approved drafts (art-pack-triage verdict, 2026-10-06). No redrawing.
Run with Pillow from the repo root: python3 tools/art/abilityicons.py
Reads art/abilities/src-128 and src-48 (Codex's exports, copied byte for byte from codex/hero-animation-icons @ 1e1aa794,
art/ability-icons-draft/processed). Writes 16/24/36/48 px PNGs, manifest.json and ability-icons.js to art/abilities/game-v1.
48 is Codex's native export; 36, 24 and 16 come from the 128 px export (premultiplied downsample, alpha threshold,
quantize without dither, pad), the same bake as tools/art/actionicons.py.
"""
from pathlib import Path
from PIL import Image
import json, base64, hashlib
ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "art/abilities"
OUT = SRC / "game-v1"
SIZES = (16, 24, 36, 48)
# live ability id -> Codex icon id (art-pack-triage). HEROES lists the 14 live ids of each hero that has a whole pack.
MAP = {
  "wren": {"batswarm": "hero-01-02", "deadeye": "hero-01-03", "sonic": "hero-01-04", "shadowstep": "hero-01-05",
           "moonvolley": "hero-01-06", "finalecho": "hero-01-07", "nighthunter": "hero-01-10",
           "huntmark": "shared-ranger-04", "volley": "shared-ranger-05", "twinshot": "shared-ranger-06"},
  "tobin": {"ironwill": "hero-02-03", "laststand": "hero-02-07", "bulwark": "hero-02-10", "heavystrike": "shared-warrior-01",
            "cleave": "shared-warrior-02", "sundering": "shared-warrior-03", "brace": "shared-warrior-04",
            "lunge": "shared-warrior-05", "momentum": "shared-warrior-06", "riposte": "hero-02-02", "roar": "hero-02-04",
            "hammerfall": "hero-02-05", "bash": "hero-02-01"},
  "pip": {"kindle": "hero-03-02", "ignite": "hero-03-03", "searing": "hero-03-04", "wildfire": "hero-03-05", "flare": "hero-03-06",
          "lanternburst": "hero-03-07", "emberheart": "hero-03-10", "spark": "shared-mage-01", "frostshard": "shared-mage-02",
          "arcaneward": "shared-mage-03", "hex": "shared-mage-04", "nova": "shared-mage-05", "afterglow": "shared-mage-06"},
}
def pixels(im):
    return im.get_flattened_data() if hasattr(im, "get_flattened_data") else im.getdata()
def bake(im, n):
    alpha = im.getchannel("A")
    bounds = alpha.point(lambda a: 255 if a >= 128 else 0).getbbox()
    if not bounds: raise ValueError("empty source")
    im = im.crop(bounds)
    pad = 1 if n <= 24 else 2
    scale = (n - 2 * pad) / max(im.size)
    w, h = (max(1, round(v * scale)) for v in im.size)
    small = im.convert("RGBa").resize((w, h), Image.Resampling.LANCZOS).convert("RGBA")
    mask = small.getchannel("A").point(lambda a: 255 if a >= 128 else 0)
    rgb = small.convert("RGB")
    visible = [p for p, a in zip(pixels(rgb), pixels(mask)) if a]
    samples = Image.new("RGB", (len(visible), 1)); samples.putdata(visible)
    palette = samples.quantize(colors=24, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    q = rgb.quantize(palette=palette, dither=Image.Dither.NONE).convert("RGBA")
    q.putalpha(mask)
    canvas = Image.new("RGBA", (n, n), (0, 0, 0, 0))
    canvas.paste(q, ((n - w) // 2, (n - h) // 2), q)
    return canvas
def main():
    OUT.mkdir(parents=True, exist_ok=True)
    pack = {"version": 1, "sizes": list(SIZES), "source": "codex/hero-animation-icons @ 1e1aa794, art/ability-icons-draft/processed", "icons": {}}
    for hero, rows in MAP.items():
        for ab, cid in rows.items():
            s128 = SRC / "src-128" / f"{cid}-128.png"; s48 = SRC / "src-48" / f"{cid}-48.png"
            item = {"hero": hero, "codex": cid, "files": {}, "data": {}}
            for size in SIZES:
                if size == 48:
                    with Image.open(s48) as im: im = im.convert("RGBA")
                    assert im.size == (48, 48)
                else:
                    with Image.open(s128) as src: im = bake(src.convert("RGBA"), size)
                name = f"{ab}-{size}.png"
                im.save(OUT / name, optimize=True)
                raw = (OUT / name).read_bytes()
                assert im.size == (size, size) and set(pixels(im.getchannel("A"))) <= {0, 255}
                item["files"][str(size)] = {"path": name, "bytes": len(raw), "sha256": hashlib.sha256(raw).hexdigest()}
                item["data"][str(size)] = "data:image/png;base64," + base64.b64encode(raw).decode()
            pack["icons"][ab] = item
    (OUT / "manifest.json").write_text(json.dumps({k: {kk: vv for kk, vv in v.items() if kk != "data"} for k, v in pack["icons"].items()}, indent=1), encoding="utf-8")
    emb = {k: {"hero": v["hero"], "data": v["data"]} for k, v in pack["icons"].items()}
    (OUT / "ability-icons.js").write_text("// Generated by tools/art/abilityicons.py from Codex's ability icon drafts. ABILITY_ICONS[id] = { hero, data: { size: PNG data URI } }.\nconst ABILITY_ICONS=" + json.dumps(emb, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(len(pack["icons"]), "abilities x", len(SIZES), "sizes")
if __name__ == "__main__": main()
