"""C26: deterministic export of owner-approved action art. No new drawing.
Run with Pillow: python tools/art/actionicons.py
Outputs only art/actions/game-v1; runtime wiring belongs to Claude.
"""
from pathlib import Path
from PIL import Image
import json, base64, io, hashlib
ROOT=Path(__file__).resolve().parents[2]
SRC=ROOT/"art/actions/review-v1"
OUT=ROOT/"art/actions/game-v1"
SIZES=(16,24,36,48)
def pixels(im):
    return im.get_flattened_data() if hasattr(im,"get_flattened_data") else im.getdata()
def bake(im,n):
    alpha=im.getchannel("A")
    bounds=alpha.point(lambda a:255 if a>=128 else 0).getbbox()
    if not bounds: raise ValueError("empty source")
    im=im.crop(bounds)
    pad=1 if n<=24 else 2
    scale=(n-2*pad)/max(im.size)
    w,h=(max(1,round(v*scale)) for v in im.size)
    # Premultiplied-alpha resize avoids dark/coloured transparent-edge halos.
    small=im.convert("RGBa").resize((w,h),Image.Resampling.LANCZOS).convert("RGBA")
    mask=small.getchannel("A").point(lambda a:255 if a>=128 else 0)
    rgb=small.convert("RGB")
    # Quantize only visible colour samples: transparent RGB must not consume palette entries.
    visible=[p for p,a in zip(pixels(rgb),pixels(mask)) if a]
    samples=Image.new("RGB",(len(visible),1)); samples.putdata(visible)
    palette=samples.quantize(colors=24,method=Image.Quantize.MEDIANCUT,dither=Image.Dither.NONE)
    q=rgb.quantize(palette=palette,dither=Image.Dither.NONE).convert("RGBA")
    q.putalpha(mask)
    canvas=Image.new("RGBA",(n,n),(0,0,0,0))
    canvas.paste(q,((n-w)//2,(n-h)//2),q)
    return canvas
def main():
    source=json.loads((SRC/"manifest.json").read_text(encoding="utf-8"))
    assert source["status"]=="owner-approved-neutral-v2"
    OUT.mkdir(parents=True,exist_ok=True)
    pack={"version":1,"sizes":list(SIZES),"defaultSize":48,"sourceApproval":"neutral-v2, owner approved 2026-10-01","icons":{}}
    for row in source["icons"]:
        atlas=SRC/row["atlas"]
        with Image.open(atlas) as sheet:
            x,y,w,h=row["rect"]
            assert x>=0 and y>=0 and x+w<=sheet.width and y+h<=sheet.height
            crop=sheet.convert("RGBA").crop((x,y,x+w,y+h))
        item={"name":row["name"],"family":row["family"],"source":row["atlas"],"sourceSha256":hashlib.sha256(atlas.read_bytes()).hexdigest(),"rect":row["rect"],"files":{},"data":{}}
        for size in SIZES:
            im=bake(crop,size)
            name=f'{row["id"]}-{size}.png'
            im.save(OUT/name,optimize=True)
            raw=(OUT/name).read_bytes()
            assert im.size==(size,size)
            assert set(pixels(im.getchannel("A")))=={0,255}
            colours={p[:3] for p in pixels(im) if p[3]}
            assert len(colours)<=24
            bb=im.getchannel("A").getbbox()
            assert bb and bb[0]>0 and bb[1]>0 and bb[2]<size and bb[3]<size
            item["files"][str(size)]={"path":name,"bytes":len(raw),"colours":len(colours),"bounds":list(bb),"sha256":hashlib.sha256(raw).hexdigest()}
            item["data"][str(size)]="data:image/png;base64,"+base64.b64encode(raw).decode()
        pack["icons"][row["id"]]=item
    assert len(pack["icons"])==16
    (OUT/"manifest.json").write_text(json.dumps(pack,indent=2),encoding="utf-8")
    embedded={k:v["data"] for k,v in pack["icons"].items()}
    (OUT/"action-icons.js").write_text("// Generated by tools/art/actionicons.py. Approved C26 artwork, neutral shared UI.\n// ACTION_ICONS[id][size] -> self-contained PNG data URI. Native sizes16/24/36/48.\nconst ACTION_ICONS="+json.dumps(embedded,separators=(",",":"))+";\n",encoding="utf-8")
    report=f'PASS:16 assets x4 sizes =64 PNGs; exact dimensions; transparent padding; binary alpha; <=24 visible colours; source/PNG SHA256 recorded.\nPNG total: {sum(f["bytes"] for v in pack["icons"].values() for f in v["files"].values())} bytes.\nEmbedded JS: {(OUT/"action-icons.js").stat().st_size} bytes.\n'
    (OUT/"validation.txt").write_text(report,encoding="utf-8")
    print(report)
if __name__=="__main__":main()