// Embed the owner-approved C26 icon packs in the game, keeping only the native sizes the UI shows.
// Reads Codex's exports (art/actions/game-v1/action-icons.js, art/navigation/game-v1/navigation-icons.js) as they
// are, and writes src/js/21s-data-actionicons.js (ACTION_ICONS), src/js/21t-data-navicons.js (NAV_ICONS) and
// src/js/21u-data-gearicons.js (GEAR_ICONS, from art/gear/game-v2/gear-icons.js).
// Nothing is redrawn or rescaled: each image is the exported PNG, byte for byte.
// Usage: node tools/art/embed-icons.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

// The sizes the CSS shows (60-solo.css .sb-ic 48/36/24 and .sp-ic 36; 30-panels/80-landscape .tab img 20/22,
// .menu-ic 22, .bell img 22, 60-nav .ap-ic 18/12, .mode-ic 16).
const PACKS = [
  { src: 'art/actions/game-v1/action-icons.js', name: 'ACTION_ICONS', out: 'src/js/21s-data-actionicons.js', sizes: [24, 36, 48] },
  { src: 'art/navigation/game-v1/navigation-icons.js', name: 'NAV_ICONS', out: 'src/js/21t-data-navicons.js', sizes: [12, 16, 18, 20, 22] },
  // Gear (C26, all 330 owner-approved): item tiles show them at 22-48 px (.ic img 28, craft 32, hero sheet 24/48,
  // gathering 26/40; 48 is 24 at x2, 60n-nicons). Only grades 1-5 exist in the game today; add 6-15 here when those tiers do.
  { src: 'art/gear/game-v2/gear-icons.js', name: 'GEAR_ICONS', out: 'src/js/21u-data-gearicons.js', sizes: [24, 32], keep: id => +id.split('-g')[1] <= 5 }
];

for (const p of PACKS) {
  const text = fs.readFileSync(path.join(ROOT, p.src), 'utf8');
  const data = new Function(text + `\nreturn ${p.name};`)();
  const out = {};
  for (const [id, bySize] of Object.entries(data)) {
    if (p.keep && !p.keep(id)) continue;
    out[id] = {};
    for (const s of p.sizes) {
      const u = bySize[s];
      if (typeof u !== 'string' || !u.startsWith('data:image/png;base64,')) throw new Error(`${p.name}.${id}: no ${s} px image`);
      out[id][s] = u;
    }
  }
  const body = `// ${path.basename(p.out, '.js')}: GENERATED by tools/art/embed-icons.mjs from ${p.src} (C26, owner-approved). Do not edit.\n` +
    `// ${p.name}[id][size] -> PNG data URI at native size (${p.sizes.join(', ')} px). Read by 60n-nicons.js. Pure data.\n` +
    `const ${p.name} = ${JSON.stringify(out)};\n`;
  fs.writeFileSync(path.join(ROOT, p.out), body);
  console.log(`wrote ${p.out}: ${Object.keys(out).length} icons x ${p.sizes.length} sizes, ${Math.round(body.length / 1024)} KB`);
}
