// Embed Tobin's route S fight pack (art/heroes/tobin/route-s, made by tools/art/route-s-tobin.py) into src/js/21yf-data-tobin-s.js.
// The atlases keep their converted WebP bytes (basE91 text, tools/lib/b91.mjs). 64n-tobin-s.js draws them.
// Usage: node tools/art/embed-tobin-s.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { B91, b91Json } from '../lib/b91.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const D = path.join(ROOT, 'art', 'heroes', 'tobin', 'route-s'), OUT = path.join(ROOT, 'src', 'js', '21yf-data-tobin-s.js');
const P = JSON.parse(fs.readFileSync(path.join(D, 'pack.json'), 'utf8'));
const file = n => new B91(fs.readFileSync(path.join(D, n)));
// the moves in the order the split build loads them after boot (tools/build.mjs hero packs: the idle is the core, at boot; then
// what a first fight shows, then the camp pose, then the abilities)
const FIRST = ['idle', 'attack', 'dash', 'dashback', 'hit', 'parry', 'dodge', 'victory', 'defeat'];
const moves = {};
for (const [mv, M] of Object.entries(P.moves).sort(([a], [b]) => (FIRST.includes(a) ? FIRST.indexOf(a) : 99) - (FIRST.includes(b) ? FIRST.indexOf(b) : 99))) {
  // f: [atlas x, y, w, h, feet anchor x, y] per kept frame; play: the frames played, as slots in f (-1: idle-1, reused);
  // hit: the place in play where the move meets its foe; catch (Shield Throw), dash (a move that dashes in) when set
  moves[mv] = { play: M.play, hit: M.hit, f: M.f.map(f => [...f.r, f.ax, f.ay]), atlas: file(mv + '.webp') };
  if (M.catch != null) moves[mv].catch = M.catch;
  if (M.dash) moves[mv].dash = 1;
  if (M.tip) moves[mv].tip = M.tip;
  if (M.sh) moves[mv].sh = M.sh;
}
// the effects ride in the move that throws them, so the split build loads them in its pack: xa the atlas, xf its rects
Object.assign(moves.shieldthrow, { xa: file('shield.webp'), xf: P.shield.f });
Object.assign(moves.hammerfall, { xa: file('rubble.webp'), xf: [...P.rubble.rocks, P.rubble.crack] });
const data = { v: 1, moves };
const body = '// 21yf-data-tobin-s: GENERATED by tools/art/embed-tobin-s.mjs from art/heroes/tobin/route-s (tools/art/route-s-tobin.py). Do not edit.\n' +
  '// TOBIN_S: Tobin\'s route S fight moves (docs/design/route-s/ruling-tobin.md), hair-top 180 art px, one 63-colour palette, 1-bit alpha,\n' +
  '// lossless WebP per move. { v, moves: { <move>: { play: [slots in f, -1 = idle-1], hit: its place in play, catch?, dash?,\n' +
  '//   f: [[atlas x, y, w, h, feet anchor x, y], ...] (the frames played; the idle: its held frame alone), atlas, tip (Hammerfall:\n' +
  '//   the sword tip on its hit frame, from the feet), sh (Shield Throw: the shield\'s centre from the feet at the release and the catch, per play position, else 0),\n' +
  '//   xa, xf (Shield Throw: the shield\'s 4 views, front, three-quarter, edge-on, back; Hammerfall: 5 rocks, then the crack): an\n' +
  '//   effect atlas and its [x, y, w, h] rects } } }. Each atlas is basE91 text (tools/lib/b91.mjs). Read by 64n-tobin-s.js. Pure data.\n' +
  `const TOBIN_S = ${b91Json(data)};\n`;
if (process.argv.includes('--check')) {
  if (!fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== body) { console.error('21yf-data-tobin-s.js is out of date: run node tools/art/embed-tobin-s.mjs'); process.exit(1); }
  console.log('21yf-data-tobin-s.js is up to date');
} else { fs.writeFileSync(OUT, body); console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(body.length / 1024)} KB)`); }
