// Pack approved enemy animation packs (art/enemies/<key>/<version>, Codex) into src/js/21za-data-foeart.js.
// The atlases keep their approved PNG bytes (base64; the packs are not palette art, so palette + RLE would change them).
// Every frame keeps its manifest timing and atlas cell, plus the left edge of its body (how far the blade reaches) and
// whether it is the empty terminal frame. 64j-foe-art.js draws them; 59l-zone-foes.js reads the timings.
// Usage: node tools/art/embed-foes.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readPNG } from '../heroart.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = path.join(ROOT, 'src', 'js', '21za-data-foeart.js');
// stage key -> pack folder (owner-approved packs only)
const PACKS = { imp: 'art/enemies/thorn-imp/approved-v2' };
const leftEdge = img => {   // first column with an opaque pixel (-1: empty)
  for (let x = 0; x < img.w; x++) for (let y = 0; y < img.h; y++) if (img.rgba[(y * img.w + x) * 4 + 3]) return x;
  return -1;
};
const data = {};
for (const [key, dir] of Object.entries(PACKS)) {
  const D = path.join(ROOT, dir), man = JSON.parse(fs.readFileSync(path.join(D, 'manifest.json'), 'utf8'));
  const atlases = {}, acts = {};
  const atlas = rel => { if (!(rel in atlases)) atlases[rel] = fs.readFileSync(path.join(D, rel)).toString('base64'); return rel; };
  for (const [id, a] of Object.entries(man.actions)) {
    const A = { loop: a.loop ? 1 : 0, start: a.action_start_frame || 1, end: a.frames.length, rel: a.release_cues || [], con: a.contacts || [],
      body: atlas(a.body_atlas), atk: a.attack_fx_atlas ? atlas(a.attack_fx_atlas) : '', hit: a.landed_hit_fx_atlas ? atlas(a.landed_hit_fx_atlas) : '', f: [] };
    // a trailing review-only idle hold is not played in the game
    const idle = a.preview_idle_frames || [];
    if (idle.includes(a.frames.length)) A.end = a.frames.length - 1;
    for (const f of a.frames) {
      const img = readPNG(path.join(D, f.body)), x0 = leftEdge(img);
      if (img.w !== man.body_cell[0] || img.h !== man.body_cell[1]) throw new Error(`${f.body}: not ${man.body_cell.join('x')}`);
      // [ms, body x, body y, body left edge (-1 empty), attack fx x, y (or -1), landed-hit fx x, y (or -1)]
      A.f.push([f.duration_ms, f.body_rect[0], f.body_rect[1], x0,
        f.attack_fx_rect ? f.attack_fx_rect[0] : -1, f.attack_fx_rect ? f.attack_fx_rect[1] : -1,
        f.landed_hit_fx_rect ? f.landed_hit_fx_rect[0] : -1, f.landed_hit_fx_rect ? f.landed_hit_fx_rect[1] : -1]);
    }
    acts[id] = A;
  }
  data[key] = { v: 2, cell: man.body_cell, origin: man.body_origin, fxCell: man.fx_cell, fxOrigin: man.fx_origin,
    hopMove: man.hop.horizontal_translation_during_ms, atlases, acts };
}
const body = '// 21za-data-foeart: GENERATED by tools/art/embed-foes.mjs from the approved enemy packs (art/enemies). Do not edit.\n' +
  '// FOE_ART = { <stage key>: { v: 2, cell, origin, fxCell, fxOrigin, hopMove: [from ms, to ms], atlases: { <path>: png base64 },\n' +
  '//   acts: { <action>: { loop, start, end, rel, con (one-based frames), body, atk, hit (atlas paths),\n' +
  '//     f: [[ms, body x, body y, body left edge, attack fx x, y, landed-hit fx x, y], ...] } } } }\n' +
  '// Read by 64j-foe-art.js (drawing) and 59l-zone-foes.js (timings). Pure data.\n' +
  `const FOE_ART = ${JSON.stringify(data)};\n`;
if (process.argv.includes('--check')) { if (!fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== body) { console.error('21za-data-foeart.js is out of date: run node tools/art/embed-foes.mjs'); process.exit(1); } console.log('21za-data-foeart.js up to date'); }
else { fs.writeFileSync(OUT, body); console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(body.length / 1024)} KB)`); }
