// Pack approved enemy art packs (art/enemies/<key>/<version>, Codex) into src/js/21za-data-foeart.js. The frames keep
// their approved PNG bytes (base64; the packs are not palette art, so palette + RLE would change them) and their
// manifest's ground anchors. 64j-foe-art.js decodes them. Usage: node tools/art/embed-foes.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = path.join(ROOT, 'src', 'js', '21za-data-foeart.js');
// stage key -> pack folder (owner-approved packs only)
const PACKS = { imp: 'art/enemies/thorn-imp/v1' };
const data = {};
for (const [key, dir] of Object.entries(PACKS)) {
  const man = JSON.parse(fs.readFileSync(path.join(ROOT, dir, 'manifest.json'), 'utf8'));
  const frames = {};
  for (const f of man.frames) {
    const b = fs.readFileSync(path.join(ROOT, dir, f.file));
    if (b.readUInt32BE(16) !== man.frame_size[0] || b.readUInt32BE(20) !== man.frame_size[1]) throw new Error(`${f.file}: not ${man.frame_size.join('x')}`);
    frames[f.id] = [f.ground_anchor[0], f.ground_anchor[1], b.toString('base64'), f.bounds[0]];
  }
  data[key] = { w: man.frame_size[0], h: man.frame_size[1], frames };
}
const body = '// 21za-data-foeart: GENERATED by tools/art/embed-foes.mjs from the approved enemy packs (art/enemies). Do not edit.\n' +
  '// FOE_ART = { <stage key>: { w, h, frames: { <pose id>: [anchorX, anchorY, png base64, left edge x] } } }. Read by 64j-foe-art.js.\n' +
  `const FOE_ART = ${JSON.stringify(data)};\n`;
if (process.argv.includes('--check')) { if (!fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== body) { console.error('21za-data-foeart.js is out of date: run node tools/art/embed-foes.mjs'); process.exit(1); } console.log('21za-data-foeart.js up to date'); }
else { fs.writeFileSync(OUT, body); console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(body.length / 1024)} KB)`); }
