// Pack approved enemy animation packs (art/enemies/<key>/<version>, Codex) into src/js/21za-data-foeart.js.
// The atlases keep their approved PNG bytes (basE91 text, tools/lib/b91.mjs, read back as base64 by 21zz-art-b91; the packs are not palette art, so palette + RLE would change them).
// Every frame keeps its manifest timing and atlas cell, plus the left edge of its body (how far the blade reaches) and
// whether it is the empty terminal frame. 64j-foe-art.js draws them; 59l-zone-foes.js reads the timings.
// Usage: node tools/art/embed-foes.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readPNG } from '../heroart.mjs';
import { B91, b91Json } from '../lib/b91.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = path.join(ROOT, 'src', 'js', '21za-data-foeart.js');
// stage key -> pack folder (owner-approved packs only)
const PACKS = { imp: 'art/enemies/thorn-imp/approved-v2', gloomjaw: 'art/enemies/gloomjaw/approved-v1' };
const leftEdge = img => {   // first column with an opaque pixel (-1: empty)
  for (let x = 0; x < img.w; x++) for (let y = 0; y < img.h; y++) if (img.rgba[(y * img.w + x) * 4 + 3]) return x;
  return -1;
};
const data = {};
const r2 = n => Math.round(n * 100) / 100;
for (const [key, dir] of Object.entries(PACKS)) {
  const D = path.join(ROOT, dir), man = JSON.parse(fs.readFileSync(path.join(D, 'manifest.json'), 'utf8'));
  const atlases = {}, acts = {}, fx = {};
  const atlas = rel => { if (!(rel in atlases)) atlases[rel] = new B91(fs.readFileSync(path.join(D, rel))); return rel; };
  const cell = man.body_cell || man.cell, fxCell = man.fx_cell || man.cell;
  for (const [id, a] of Object.entries(man.actions)) {
    if (a.layer === 'fx') {   // a separate effect (Gloomjaw): [ms, atlas x, atlas y]
      fx[id] = { loop: a.loop ? 1 : 0, atlas: atlas(a.atlas), f: a.frames.map(f => [r2(f.duration_ms), f.rect[0], f.rect[1]]) };
      continue;
    }
    const ev = a.events || [], evF = k => ev.filter(e => e.kind === k).map(e => e.frame);
    const A = { loop: a.loop ? 1 : 0, start: a.action_start_frame || 1, end: a.frames.length,
      rel: a.release_cues || evF('projectile_release'), con: a.contacts || evF('contact'),
      body: atlas(a.body_atlas || a.atlas), atk: a.attack_fx_atlas ? atlas(a.attack_fx_atlas) : '', hit: a.landed_hit_fx_atlas ? atlas(a.landed_hit_fx_atlas) : '', f: [] };
    // a trailing review-only idle hold is not played in the game
    const idle = a.preview_idle_frames || [];
    if (idle.includes(a.frames.length)) A.end = a.frames.length - 1;
    for (const f of a.frames) {
      const img = readPNG(path.join(D, f.body || f.file)), x0 = leftEdge(img), br = f.body_rect || f.rect;
      if (img.w !== cell[0] || img.h !== cell[1]) throw new Error(`${f.body || f.file}: not ${cell.join('x')}`);
      // [ms, body x, body y, body left edge (-1 empty), attack fx x, y (or -1), landed-hit fx x, y (or -1)]
      A.f.push([r2(f.duration_ms), br[0], br[1], x0,
        f.attack_fx_rect ? f.attack_fx_rect[0] : -1, f.attack_fx_rect ? f.attack_fx_rect[1] : -1,
        f.landed_hit_fx_rect ? f.landed_hit_fx_rect[0] : -1, f.landed_hit_fx_rect ? f.landed_hit_fx_rect[1] : -1]);
    }
    acts[id] = A;
  }
  const hop = man.hop || {};
  data[key] = { v: 2, cell, origin: man.body_origin, fxCell, fxOrigin: man.fx_origin,
    hopMove: hop.horizontal_translation_during_ms || hop.horizontal_translation_ms, mouth: man.mouth_effect_offset_from_world_root || null,
    atlases, acts, fx };
}
const body = '// 21za-data-foeart: GENERATED by tools/art/embed-foes.mjs from the approved enemy packs (art/enemies). Do not edit.\n' +
  '// FOE_ART = { <stage key>: { v: 2, cell, origin, fxCell, fxOrigin, hopMove: [from ms, to ms], mouth: [dx, dy] from the root or null,\n' +
  '//   atlases: { <path>: png, basE91 (reads back as base64, 21zz-art-b91) }, fx: { <effect>: { loop, atlas, f: [[ms, x, y], ...] } } (separate effects),\n' +
  '//   acts: { <action>: { loop, start, end, rel, con (one-based frames), body, atk, hit (atlas paths),\n' +
  '//     f: [[ms, body x, body y, body left edge, attack fx x, y, landed-hit fx x, y], ...] } } } }\n' +
  '// Read by 64j-foe-art.js (drawing) and 59l-zone-foes.js (timings). Pure data.\n' +
  `const FOE_ART = ${b91Json(data)};\n`;
if (process.argv.includes('--check')) { if (!fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== body) { console.error('21za-data-foeart.js is out of date: run node tools/art/embed-foes.mjs'); process.exit(1); } console.log('21za-data-foeart.js up to date'); }
else { fs.writeFileSync(OUT, body); console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(body.length / 1024)} KB)`); }
