// Embed Wren's route S fight pack (art/heroes/wren/route-s, made by tools/art/route-s-wren.py) into src/js/21ye-data-wren-s.js.
// The atlases keep their converted WebP bytes (basE91 text, tools/lib/b91.mjs). 64l-wren-s.js draws them.
// Usage: node tools/art/embed-wren-s.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { B91, b91Json } from '../lib/b91.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const D = path.join(ROOT, 'art', 'heroes', 'wren', 'route-s'), OUT = path.join(ROOT, 'src', 'js', '21ye-data-wren-s.js');
const P = JSON.parse(fs.readFileSync(path.join(D, 'pack.json'), 'utf8'));
const file = n => new B91(fs.readFileSync(path.join(D, n)));
// the moves in the order the split build loads them after boot (tools/build.mjs hero packs: the idle is the core, at boot; then
// what a first fight shows, then the camp pose, then the abilities)
const FIRST = ['idle', 'attack', 'twinshot', 'hit', 'parry', 'dodge', 'victory', 'defeat'];
const moves = {};
for (const [mv, M] of Object.entries(P.moves).sort(([a], [b]) => (FIRST.includes(a) ? FIRST.indexOf(a) : 99) - (FIRST.includes(b) ? FIRST.indexOf(b) : 99))) {
  // f: [atlas x, y, w, h, feet anchor x, y] per frame; s: the string's [top, bottom, hand or null] as offsets from the feet
  // anchor (art px), 0 for a frame with no game-drawn string, or no s at all (the 8 moves with a painted string)
  moves[mv] = { rel: M.rel, f: M.f.map(f => [...f.r, f.ax, f.ay]), atlas: file(mv + '.webp') };
  if (M.f.some(f => 'str' in f)) moves[mv].s = M.f.map(f => f.str || 0);
}
const data = { v: 1, string: P.string, moves,
  arrows: { atlas: file('arrows.webp'), r: Object.fromEntries(Object.entries(P.arrows).map(([k, a]) => [k, a.r])) },
  bats: { atlas: file('bats.webp'), f: P.bats.f, at: P.bats.at } };
const body = '// 21ye-data-wren-s: GENERATED by tools/art/embed-wren-s.mjs from art/heroes/wren/route-s (tools/art/route-s-wren.py). Do not edit.\n' +
  '// WREN_S: Wren\'s route S fight moves (ruling #328, docs/design/route-s/ruling.md), 190 art px tall, one 63-colour palette, 1-bit alpha,\n' +
  '// lossless WebP per move. { v, string: the painted string\'s colour (hex), moves: { <move>: { rel: [release frames, 0-based],\n' +
  '//   f: [[atlas x, y, w, h, feet anchor x, y], ...] (8 frames; the idle: its held frame alone), s: [[top, bottom, hand | null]\n' +
  '//   offsets from the feet | 0, ...] (shooting moves only), atlas } }, arrows: { atlas, r: { plain, heavy, sonic: [x, y, w, h] } },\n' +
  '//   bats: { atlas, f: [[x, y, w, h] x6], at: [dx, dy] from the feet anchor } }. Each atlas is basE91 text (tools/lib/b91.mjs). Read by 64l-wren-s.js. Pure data.\n' +
  `const WREN_S = ${b91Json(data)};\n`;
if (process.argv.includes('--check')) {
  if (!fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== body) { console.error('21ye-data-wren-s.js is out of date: run node tools/art/embed-wren-s.mjs'); process.exit(1); }
  console.log('21ye-data-wren-s.js is up to date');
} else { fs.writeFileSync(OUT, body); console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(body.length / 1024)} KB)`); }
