// Pack approved fixed battle backgrounds (art/backgrounds/<place>/<version>, Codex) into src/js/21zb-data-bgart.js.
// The lossless WebP exports keep their approved bytes (base64). 62-stage draws them (smooth sampling) behind the actors.
// Usage: node tools/art/embed-bg.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = path.join(ROOT, 'src', 'js', '21zb-data-bgart.js');
// scene theme -> pack, and the export used for each orientation (owner-approved packs only)
const PACKS = {
  forest: { dir: 'art/backgrounds/mossy-hollow/outlined-night-v1', land: 'runtime/mossy-hollow-night-960x540.webp', port: 'runtime/mossy-hollow-night-portrait-480x900.webp' }
};
const data = {};
for (const [theme, P] of Object.entries(PACKS)) {
  const D = path.join(ROOT, P.dir), man = JSON.parse(fs.readFileSync(path.join(D, 'manifest.json'), 'utf8'));
  const exp = (list, file) => { const e = list.find(x => x.path === file); if (!e) throw new Error(`${file}: not in the manifest`); return e; };
  const L = exp(man.exports, P.land), Q = exp(man.portrait.exports, P.port);
  data[theme] = { id: man.id,
    land: { w: L.width, h: L.height, road: man.suggestedFeetYNormalized, src: fs.readFileSync(path.join(D, P.land)).toString('base64') },
    port: { w: Q.width, h: Q.height, road: man.portrait.suggestedFeetYNormalized, src: fs.readFileSync(path.join(D, P.port)).toString('base64') } };
}
const body = '// 21zb-data-bgart: GENERATED by tools/art/embed-bg.mjs from the approved fixed battle backgrounds (art/backgrounds). Do not edit.\n' +
  '// BG_ART = { <scene theme>: { id, land, port } }, each { w, h, road (the painted road, where feet stand, as a share of the\n' +
  '// height), src (lossless WebP, base64) }. Drawn by 62-stage. Pure data.\n' +
  `const BG_ART = ${JSON.stringify(data)};\n`;
if (process.argv.includes('--check')) { if (!fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== body) { console.error('21zb-data-bgart.js is out of date: run node tools/art/embed-bg.mjs'); process.exit(1); } console.log('21zb-data-bgart.js up to date'); }
else { fs.writeFileSync(OUT, body); console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(body.length / 1024)} KB)`); }
