// Embed the owner-approved C26 icon packs in the game, keeping only the native sizes the UI shows.
// Reads Codex's exports (art/actions/game-v1/action-icons.js, art/navigation/game-v1/navigation-icons.js) as they
// are, and writes src/js/21s-data-actionicons.js (ACTION_ICONS), src/js/21t-data-navicons.js (NAV_ICONS) and
// src/js/21u-data-gearicons.js (GEAR_ICONS, from art/gear/game-v2/gear-icons.js) and src/js/21v-data-statusicons.js (STATUS_ICONS).
// Nothing is redrawn or rescaled: each image is the exported PNG, byte for byte, written as basE91 text (tools/lib/b91.mjs;
// src/js/21zz-art-b91.js gives the readers the same data URI back).
// Usage: node tools/art/embed-icons.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { B91, b91Json } from '../lib/b91.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

// The sizes the CSS shows (60-solo.css .sb-ic 48/36/24, .sp-ic 36, .ab-ic 16 (the Auto badge); 30-panels/80-landscape .tab img 20/22,
// .menu-ic 22, .bell img 22, 60-nav .ap-ic 18/12, .mode-ic 16).
const PACKS = [
  // Ability icons (Codex drafts, converted by tools/art/abilityicons.py) join ACTION_ICONS under the live ability id, but only
  // for a hero whose whole pack is drawn (art freeze: no partial packs). Pip is whole; Wren and Tobin wait for four more icons.
  { src: 'art/actions/game-v1/action-icons.js', name: 'ACTION_ICONS', out: 'src/js/21s-data-actionicons.js', sizes: [16, 24, 36, 48],
    extra: { src: 'art/abilities/game-v1/ability-icons.js', name: 'ABILITY_ICONS', heroes: ['pip'], sizes: [24, 36, 48] } },
  { src: 'art/navigation/game-v1/navigation-icons.js', name: 'NAV_ICONS', out: 'src/js/21t-data-navicons.js', sizes: [12, 16, 18, 20, 22] },
  // Gear (C26, all 330 owner-approved): item tiles show them at 22-48 px (.ic img 28, craft 32, hero sheet 24/48,
  // gathering 26/40; 48 native in the hero gear rows and 96 = 48 at x2 on the item card, gear-icons-48). Only grades 1-5 exist in the game today; add 6-15 here when those tiers do.
  // Status icons (C26, all 15 owner-approved, 2026-10-01): the stage's status chips (62-stage chip/badge) draw them at the
  // native size nearest the HUD pixel (U): about 6U device px, so 16-48.
  { src: 'art/status/game-v1/status-icons.js', name: 'STATUS_ICONS', out: 'src/js/21v-data-statusicons.js', sizes: [16, 24, 36, 48] },
  { src: 'art/gear/game-v2/gear-icons.js', name: 'GEAR_ICONS', out: 'src/js/21u-data-gearicons.js', sizes: [24, 32, 48], keep: id => +id.split('-g')[1] <= 5 }
];

const png = u => { if (!u.startsWith('data:image/png;base64,')) throw new Error('not a PNG data URI'); return new B91(Buffer.from(u.slice(22), 'base64')); };
for (const p of PACKS) {
  const text = fs.readFileSync(path.join(ROOT, p.src), 'utf8');
  const data = new Function(text + `\nreturn ${p.name};`)();
  const out = {};
  for (const [id, bySize] of Object.entries(data)) {
    if (p.keep && !p.keep(id)) continue;
    out[id] = {};
    for (const s of p.sizes) {
      const u = bySize[s];
      if (typeof u !== 'string' || !u.startsWith('data:image/png;base64,')) throw new Error(`${p.name}.${id}: no ${s} px image`);
      out[id][s] = png(u);
    }
  }
  if (p.extra) {
    const x = new Function(fs.readFileSync(path.join(ROOT, p.extra.src), 'utf8') + `\nreturn ${p.extra.name};`)();
    for (const [id, row] of Object.entries(x)) {
      if (!p.extra.heroes.includes(row.hero)) continue;
      if (out[id]) throw new Error(`${p.name}.${id}: already in the pack (use a swap, not an add)`);
      out[id] = {};
      for (const s of p.extra.sizes) {
        if (!row.data[s]) throw new Error(`${p.extra.name}.${id}: no ${s} px image`);
        out[id][s] = png(row.data[s]);
      }
    }
  }
  const body = `// ${path.basename(p.out, '.js')}: GENERATED by tools/art/embed-icons.mjs from ${p.src} (C26, owner-approved). Do not edit.\n` +
    `// ${p.name}[id][size] -> PNG data URI at native size (${p.sizes.join(', ')} px), embedded as basE91 (21zz-art-b91). Read by 60n-nicons.js. Pure data.\n` +
    `const ${p.name} = ${b91Json(out)};\n`;
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(path.join(ROOT, p.out)) ? fs.readFileSync(path.join(ROOT, p.out), 'utf8') : '';
    if (cur !== body) { console.error(`${p.out} is out of date: run node tools/art/embed-icons.mjs`); process.exitCode = 1; } else console.log(`${p.out} up to date`);
    continue;
  }
  fs.writeFileSync(path.join(ROOT, p.out), body);
  console.log(`wrote ${p.out}: ${Object.keys(out).length} icons x ${p.sizes.length} sizes, ${Math.round(body.length / 1024)} KB`);
}
