// Pack the interim Hunting art (art/hunting/interim-v1, made by tools/art/hunt-interim.py from Codex's drafts) into
// src/js/21z-data-huntart.js as palette + RLE (the HERO_ART format, tools/heroart.mjs), so it decodes synchronously.
// Owner (2026-10-01): wire Codex's drafts in now; Codex's vetted production pack replaces them.
// Usage: node tools/art/embed-hunt.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readPNG, encode } from '../heroart.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const DIR = path.join(ROOT, 'art', 'hunting', 'interim-v1'), OUT = path.join(ROOT, 'src', 'js', '21z-data-huntart.js');
const meta = JSON.parse(fs.readFileSync(path.join(DIR, 'meta.json'), 'utf8'));
const hx = (b, i) => ((b[i] << 16) | (b[i + 1] << 8) | b[i + 2]).toString(16).padStart(6, '0');
const palOf = imgs => { const out = []; for (const { w, h, rgba } of imgs) for (let i = 0; i < w * h; i++) if (rgba[i * 4 + 3]) { const c = hx(rgba, i * 4); if (!out.includes(c)) out.push(c); } return out; };
const data = { beasts: {}, bg: null };
for (const [key, poses] of Object.entries(meta.beasts)) {
  const imgs = poses.map(p => readPNG(path.join(DIR, `${key}-${p.pose}.png`)));
  const pal = palOf(imgs); if (pal.length > 63) throw new Error(`${key}: ${pal.length} colours (max 63)`);
  const B = { pal: pal.join(''), poses: {} };
  poses.forEach((p, i) => { const e = encode(imgs[i], pal, key + '-' + p.pose, true); B.poses[p.pose] = [p.ax, e.w, e.h, e.b64]; });
  data.beasts[key] = B;
}
{ const img = readPNG(path.join(DIR, 'hunting-grounds.png')), pal = palOf([img]);
  if (pal.length > 63) throw new Error(`background: ${pal.length} colours (max 63)`);
  const e = encode(img, pal, 'hunting-grounds', true); data.bg = { pal: pal.join(''), rec: [e.w, e.h, e.b64] }; }
const body = '// 21z-data-huntart: GENERATED by tools/art/embed-hunt.mjs from art/hunting/interim-v1 (interim Hunting art, owner 2026-10-01). Do not edit.\n' +
  '// HUNT_ART = { beasts: { <key>: { pal, poses: { <pose>: [ax, w, h, rle] } } }, bg: { pal, rec: [w, h, rle] } }  (rle: the HERO_ART format; feet\n' +
  '// on the bottom row at x = ax). Read by 64i-hunt-art.js. Pure data.\n' +
  `const HUNT_ART = ${JSON.stringify(data)};\n`;
if (process.argv.includes('--check')) { if (fs.readFileSync(OUT, 'utf8') !== body) { console.error('21z-data-huntart.js is out of date: run node tools/art/embed-hunt.mjs'); process.exit(1); } console.log('21z-data-huntart.js up to date'); }
else { fs.writeFileSync(OUT, body); console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(body.length / 1024)} KB)`); }
