#!/usr/bin/env python3
# Resource icons (C26, owner-approved 2026-10-01): cut grades 1-5 of the seven families from the approved atlases
# (art/resources/approved-v1, source rectangles in manifest.js) and bake 48x48 pixel icons: fit with a 2 px margin,
# a smooth downscale, hard alpha, and at most 32 colours per icon (no dither). 48 px divides evenly to the 16 and
# 24 px the UI shows them at. Writes art/resources/game-v1/<family>-<grade>.png and src/js/21r-data-resicons.js.
# Usage: python3 tools/art/resicons.py
import os, json, re, io
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'art', 'resources', 'approved-v1')
OUT = os.path.join(ROOT, 'art', 'resources', 'game-v1')
N, PAD, GRADES = 48, 2, 5
FAMS = ['ore', 'wood', 'fibre', 'hide', 'herb', 'crystal', 'ess']
B91 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#$%&()*+,./:;<=>?@[]^_`{|}~"'

def b91(data):   # basE91 text, as tools/lib/b91.mjs writes it (src/js/21zz-art-b91.js reads it back as the PNG data URI)
    b = n = 0; out = []
    for c in data:
        b |= c << n; n += 8
        if n > 13:
            v = b & 8191
            if v > 88: b >>= 13; n -= 13
            else: v = b & 16383; b >>= 14; n -= 14
            out += [B91[v % 91], B91[v // 91]]
    if n:
        out.append(B91[b % 91])
        if n > 7 or b > 90: out.append(B91[b // 91])
    s = ''.join(out)
    if '</script' in s.lower(): raise ValueError('basE91 text contains "</script"; refusing to embed it')
    return s

def main():
    js = open(os.path.join(SRC, 'manifest.js')).read()
    pack = json.loads(js[js.index('{'):js.rindex('}') + 1])
    sheets = {k: Image.open(os.path.join(SRC, v)).convert('RGBA') for k, v in pack['sheets'].items()}
    os.makedirs(OUT, exist_ok=True)
    data, names = {}, {}
    for ic in pack['icons']:
        fam, g = ic['family'], ic['grade']
        if fam not in FAMS or g > GRADES: continue
        f = ic['frame']
        im = sheets[ic['sheet']].crop((f['x'], f['y'], f['x'] + f['w'], f['y'] + f['h']))
        bb = im.getchannel('A').point(lambda v: 255 if v > 32 else 0).getbbox()
        if bb: im = im.crop(bb)
        k = (N - 2 * PAD) / max(im.width, im.height)
        w, h = max(1, round(im.width * k)), max(1, round(im.height * k))
        sm = im.resize((w, h), Image.LANCZOS)
        a = sm.getchannel('A').point(lambda v: 255 if v >= 128 else 0)
        q = sm.convert('RGB').quantize(colors=32, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE).convert('RGBA')
        q.putalpha(a)
        can = Image.new('RGBA', (N, N), (0, 0, 0, 0)); can.paste(q, ((N - w) // 2, N - PAD - h), q)
        p = os.path.join(OUT, f'{fam}-{g}.png'); can.save(p, optimize=True)
        buf = io.BytesIO(); can.save(buf, 'PNG', optimize=True)
        data.setdefault(fam, [None] * GRADES)[g - 1] = b91(buf.getvalue())
        names.setdefault(fam, [None] * GRADES)[g - 1] = ic['name']
    for fam in FAMS: assert all(data[fam]) and all(names[fam]), fam
    # the icons as single-quoted basE91 literals (the alphabet has no ' or \\), never through json.dumps (it would escape ")
    icons = '{' + ','.join(json.dumps(f) + ':[' + ','.join("'" + u + "'" for u in data[f]) + ']' for f in data) + '}'
    body = '{"names":' + json.dumps(names, separators=(',', ':')) + ',"icons":' + icons + '}'
    src = ('// 21r-data-resicons: GENERATED by tools/art/resicons.py from art/resources/approved-v1 (C26, owner-approved). Do not edit.\n'
           '// Resource icons, grades 1-5 of the seven families, 48x48 PNG data URIs (embedded as basE91, 21zz-art-b91), and the approved display names.\n'
           '// Read by matIcon (60-gfx.js) and MAT names (21-data-craft.js). Pure data.\n'
           'const RES_ICONS = ' + body + ';\n')
    open(os.path.join(ROOT, 'src', 'js', '21r-data-resicons.js'), 'w').write(src)
    print('wrote', len(src) // 1024, 'KB;', ', '.join(f"{f}: {'/'.join(names[f])}" for f in FAMS))

if __name__ == '__main__':
    main()
