// Pack the Claude trial art for area 1, Mossy Hollow (art/area-1, Cal's "Trial one pack", 2026-10-07) into src/js/21zc-data-art-area1.js.
// Draws every creature pack and both background orientations from the generators in art/area-1, writes the atlases as PNGs under
// art/area-1/pack/ and embeds them (base64). Deterministic: --check redraws and compares.
// Usage: node tools/embed-area-1.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildPack } from '../art/area-1/pack.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src', 'js', '21zc-data-art-area1.js'), PACK = path.join(ROOT, 'art', 'area-1', 'pack');
const defs = [['imp', '../art/area-1/imp-pack.mjs', 'impDef'], ['gloomjaw', '../art/area-1/gloomjaw.mjs', 'gloomjawDef'], ['ravager', '../art/area-1/ravager.mjs', 'ravagerDef'],
  ['thornwing', '../art/area-1/thornwing.mjs', 'thornwingDef'], ['sorcerer', '../art/area-1/sorcerer.mjs', 'sorcererDef']];
const check = process.argv.includes('--check');
const files = {}, foes = {}, bg = {};
for (const [key, file, fn] of defs) {
  const mod = await import(new URL(file, import.meta.url));
  if (!mod[fn]) continue;
  const P = buildPack(mod[fn]());
  foes[key] = P.data;
  files[`${key}-body.png`] = P.png.body; if (P.png.fx) files[`${key}-fx.png`] = P.png.fx;
}
const { drawBackground } = await import('../art/area-1/background.mjs');
const { encodePNG } = await import('../art/area-1/kit.mjs');
bg.forest = { id: 'mossy-hollow-claude-trial-v1' };
for (const [o, name] of [['land', 'land'], ['port', 'port']]) {
  const B = drawBackground(o), png = encodePNG(B.img);
  files[`bg-${name}.png`] = png;
  bg.forest[name] = { w: B.w, h: B.h, road: B.road > 1 ? B.road / B.h : B.road, src: png.toString('base64') };
}
const body = '// 21zc-data-art-area1: GENERATED by tools/embed-area-1.mjs from the Claude trial pack for area 1, Mossy Hollow (art/area-1). Do not edit.\n' +
  '// FOE_ART_CL has the shape of FOE_ART (21za) and BG_ART_CL the shape of BG_ART (21zb, but PNG). They are drawn instead of the Codex art unless the\n' +
  '// player turned Classic art on (64j-foe-art.js, 62-stage.js). Creatures the game has no zone monster for yet (ravager, thornwing, sorcerer) sit here, unused. Pure data.\n' +
  `const FOE_ART_CL = ${JSON.stringify(foes)};\nconst BG_ART_CL = ${JSON.stringify(bg)};\n`;
if (check) {
  let bad = !fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== body;
  for (const [f, buf] of Object.entries(files)) if (!fs.existsSync(path.join(PACK, f)) || !fs.readFileSync(path.join(PACK, f)).equals(buf)) bad = true;
  if (bad) { console.error('21zc-data-art-area1.js or art/area-1/pack is out of date: run node tools/embed-area-1.mjs'); process.exit(1); }
  console.log('21zc-data-art-area1.js up to date');
} else {
  fs.mkdirSync(PACK, { recursive: true });
  for (const [f, buf] of Object.entries(files)) fs.writeFileSync(path.join(PACK, f), buf);
  fs.writeFileSync(OUT, body); console.log(`wrote ${path.relative(ROOT, OUT)} (${Math.round(body.length / 1024)} KB): ${Object.keys(foes).join(', ')}`);
}
