#!/usr/bin/env node
// Pack the hero portraits (art/portraits/<id>.png, cut from the approved concept boards by tools/art/concept-portraits.py)
// into src/js/21yc-data-portraits.js (HERO_PORTRAITS: id -> PNG data URL). Each PNG goes in byte for byte.
// Usage: node tools/portraits.mjs            (writes the file)
//        node tools/portraits.mjs --check    (exit 1 if the committed file is out of date)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(ROOT, 'art', 'portraits');
const OUT = path.join(ROOT, 'src', 'js', '21yc-data-portraits.js');

export function pack() {
  const ids = fs.readdirSync(DIR).filter(f => f.endsWith('.png')).map(f => f.slice(0, -4)).sort();
  const rows = ids.map(id => `  ${JSON.stringify(id)}: 'data:image/png;base64,${fs.readFileSync(path.join(DIR, id + '.png')).toString('base64')}'`);
  const src = `// 21yc-data-portraits: GENERATED by tools/portraits.mjs from art/portraits/*.png. Do not edit.
// Hero portraits (64x64, transparent, 1 px outline) cut from the owner-approved concept boards' Face Detail vignettes.
// Keyed by concept id, which is the roster id where the hero is in the game. Shown by 64k-portraits.js.
// Pure data (a core-range file): no DOM.
const HERO_PORTRAITS = {
${rows.join(',\n')}
};
`;
  return { src, ids };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { src, ids } = pack();
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (cur !== src) { console.log('src/js/21yc-data-portraits.js is out of date: run node tools/portraits.mjs'); process.exit(1); }
    console.log('src/js/21yc-data-portraits.js is up to date');
  } else {
    fs.writeFileSync(OUT, src);
    console.log(`wrote ${path.relative(ROOT, OUT)} (${src.length} bytes, ${ids.length} portraits)`);
  }
}
